/**
 * Universidad de San Carlos de Guatemala
 * Facultad de Ingenieria
 * Ingenieria en Ciencias y Sistemas
 * Esdras Benjamin Cotto Revolorio
 * Carnet: 200412823
 */

package PlantasVrsZombies;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Ben
 */
public class Inicio extends Mi_Ventana_200412823 {

    String pathPlantaImage ="C:\\Users\\Ben\\Dropbox\\Mis docs\\EDD\\15\\Practicas\\Practica1s12015_200412823\\src\\imagenes\\planta.jpg";
    String pathZombieImage ="C:\\Users\\Ben\\Dropbox\\Mis docs\\EDD\\15\\Practicas\\Practica1s12015_200412823\\src\\imagenes\\zombie.jpg";
    String pathPlantaImageDefault ="C:\\Users\\Ben\\Dropbox\\Mis docs\\EDD\\15\\Practicas\\Practica1s12015_200412823\\src\\imagenes\\defaultPlanta.jpg";
    String pathZombieImageDefault ="C:\\Users\\Ben\\Dropbox\\Mis docs\\EDD\\15\\Practicas\\Practica1s12015_200412823\\src\\imagenes\\defaultZombie.jpg";
    String foto = "null";
    FileNameExtensionFilter filtroFotos = new FileNameExtensionFilter("JPG & GIF & PNG", "jpg", "gif","png");
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        ponerImagenLabel(pathPlantaImage, jlabelPlanta);
        ponerImagenLabel(pathZombieImage, jLabelZombie);
    }
    
    /**
     * Este metodo es para poner imagen en un label y que se ajuste al tamaño de este
     */
    public void ponerImagenLabel(String imag,JLabel etiqueta)
    {
        //Image immage = new ImageIcon(getClass().getResource(imag)).getImage();
        //Image immage = new ImageIcon(imag).getImage();
        ImageIcon fot = new ImageIcon(imag);
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(etiqueta.getWidth(), etiqueta.getHeight(), Image.SCALE_DEFAULT));
        etiqueta.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diagDatosPlayerPlantas = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombrePlayerPlantas = new javax.swing.JTextField();
        jbOkDatosPlayerPlantas = new javax.swing.JButton();
        jbCancelDatosPlayerPlantas = new javax.swing.JButton();
        txtCantidadDatosPlantas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jbMoreDatosPlayerPlantas = new javax.swing.JButton();
        jbContinuarCatalogoDatosPlayerPlantas = new javax.swing.JButton();
        diagNuevosCamposPlayerPlantas = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNewCampoPlantas = new javax.swing.JTextField();
        jbAgregarNuevoCampoPlantas = new javax.swing.JButton();
        jbFinalizarNuevosCamposPlantas = new javax.swing.JButton();
        diagDatosPlayerZombies = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtNombrePlayerZombies = new javax.swing.JTextField();
        jbOkDatosPlayerZombies = new javax.swing.JButton();
        jbCancelDatosPlayerZombies = new javax.swing.JButton();
        txtCantidadDatosZombies = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jbMoreDatosPlayerZombies = new javax.swing.JButton();
        jbContinuarCatalogoDatosPlayerZombies = new javax.swing.JButton();
        diagNuevosCamposPlayerZombies = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNewCampoZombies = new javax.swing.JTextField();
        jbAgregarNuevoCampoZombies = new javax.swing.JButton();
        jbFinalizarNuevosCamposZombies = new javax.swing.JButton();
        diagCatalogoPlantas = new javax.swing.JDialog();
        jScrollPaneCatalogoPlantas = new javax.swing.JScrollPane();
        jSeparator2 = new javax.swing.JSeparator();
        botonAgregarPlantasCatalogo = new javax.swing.JButton();
        botonFinalizaDatosPlayerPlantas = new javax.swing.JButton();
        diagNuevaPlanta = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etiquetaImagenPlanta = new javax.swing.JLabel();
        txtNombrePlantaNueva = new javax.swing.JTextField();
        txtPuntosAtaquePlantaNueva = new javax.swing.JTextField();
        txtPuntosDefensaPlantaNueva = new javax.swing.JTextField();
        botonNuevaPlanta = new javax.swing.JButton();
        botonGuardarPlantaNueva = new javax.swing.JButton();
        botonSalirIngresoPlantaNueva = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTipoAtaquePlantaNueva = new javax.swing.JTextField();
        botonConfirmNewPlanta = new java.awt.Button();
        labelConfirmacionNuevaPlanta = new java.awt.Label();
        botonAbortNewPlanta = new java.awt.Button();
        jFileChooserFotos = new javax.swing.JFileChooser();
        diagCatalogoPlantas1 = new javax.swing.JDialog();
        jScrollPaneCatalogoPlantas1 = new javax.swing.JScrollPane();
        jSeparator3 = new javax.swing.JSeparator();
        botonAgregarPlantasCatalogo1 = new javax.swing.JButton();
        botonFinalizaDatosPlayerPlantas1 = new javax.swing.JButton();
        diagNuevaPlanta1 = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        etiquetaImagenPlanta1 = new javax.swing.JLabel();
        txtNombrePlantaNueva1 = new javax.swing.JTextField();
        txtPuntosAtaquePlantaNueva1 = new javax.swing.JTextField();
        txtPuntosDefensaPlantaNueva1 = new javax.swing.JTextField();
        botonNuevaPlanta1 = new javax.swing.JButton();
        botonGuardarPlantaNueva1 = new javax.swing.JButton();
        botonSalirIngresoPlantaNueva1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTipoAtaquePlantaNueva1 = new javax.swing.JTextField();
        botonConfirmNewPlanta1 = new java.awt.Button();
        labelConfirmacionNuevaPlanta1 = new java.awt.Label();
        botonAbortNewPlanta1 = new java.awt.Button();
        jbPlayerPlantas = new javax.swing.JButton();
        jbPlayerZombie = new javax.swing.JButton();
        jbStartJuego = new javax.swing.JButton();
        jbEliminarDatos = new javax.swing.JButton();
        jlabelPlanta = new javax.swing.JLabel();
        jLabelZombie = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        diagDatosPlayerPlantas.setTitle("Player Plantas");
        diagDatosPlayerPlantas.setIconImage(getIconImage());
        diagDatosPlayerPlantas.setMaximumSize(new java.awt.Dimension(540, 280));
        diagDatosPlayerPlantas.setMinimumSize(new java.awt.Dimension(540, 280));
        diagDatosPlayerPlantas.setModal(true);
        diagDatosPlayerPlantas.setPreferredSize(new java.awt.Dimension(540, 280));
        diagDatosPlayerPlantas.setResizable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Ingrese los datos");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Nombre");
        jLabel12.setToolTipText("");

        txtNombrePlayerPlantas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombrePlayerPlantas.setToolTipText("Escriba su nombre");

        jbOkDatosPlayerPlantas.setBackground(java.awt.Color.green);
        jbOkDatosPlayerPlantas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbOkDatosPlayerPlantas.setText("Aceptar");

        jbCancelDatosPlayerPlantas.setBackground(java.awt.Color.red);
        jbCancelDatosPlayerPlantas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbCancelDatosPlayerPlantas.setText("Cancelar");
        jbCancelDatosPlayerPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelDatosPlayerPlantasActionPerformed(evt);
            }
        });

        txtCantidadDatosPlantas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadDatosPlantas.setToolTipText("Cuantas plantas quieres?");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Cantidad");

        jbMoreDatosPlayerPlantas.setBackground(java.awt.Color.blue);
        jbMoreDatosPlayerPlantas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbMoreDatosPlayerPlantas.setText("Agregar mas Campos");
        jbMoreDatosPlayerPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMoreDatosPlayerPlantasActionPerformed(evt);
            }
        });

        jbContinuarCatalogoDatosPlayerPlantas.setBackground(java.awt.Color.cyan);
        jbContinuarCatalogoDatosPlayerPlantas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbContinuarCatalogoDatosPlayerPlantas.setText("Continuar");
        jbContinuarCatalogoDatosPlayerPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbContinuarCatalogoDatosPlayerPlantasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diagDatosPlayerPlantasLayout = new javax.swing.GroupLayout(diagDatosPlayerPlantas.getContentPane());
        diagDatosPlayerPlantas.getContentPane().setLayout(diagDatosPlayerPlantasLayout);
        diagDatosPlayerPlantasLayout.setHorizontalGroup(
            diagDatosPlayerPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagDatosPlayerPlantasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diagDatosPlayerPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(diagDatosPlayerPlantasLayout.createSequentialGroup()
                        .addGroup(diagDatosPlayerPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(diagDatosPlayerPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(diagDatosPlayerPlantasLayout.createSequentialGroup()
                                .addComponent(jbMoreDatosPlayerPlantas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbContinuarCatalogoDatosPlayerPlantas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtCantidadDatosPlantas, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtNombrePlayerPlantas))
                        .addGap(18, 18, 18)
                        .addGroup(diagDatosPlayerPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbOkDatosPlayerPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCancelDatosPlayerPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diagDatosPlayerPlantasLayout.setVerticalGroup(
            diagDatosPlayerPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagDatosPlayerPlantasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(diagDatosPlayerPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNombrePlayerPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbOkDatosPlayerPlantas))
                .addGap(18, 18, 18)
                .addGroup(diagDatosPlayerPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCantidadDatosPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelDatosPlayerPlantas))
                .addGap(51, 51, 51)
                .addGroup(diagDatosPlayerPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMoreDatosPlayerPlantas)
                    .addComponent(jbContinuarCatalogoDatosPlayerPlantas))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        diagDatosPlayerPlantas.getAccessibleContext().setAccessibleParent(this);

        diagNuevosCamposPlayerPlantas.setTitle("Nuevos Campos");
        diagNuevosCamposPlayerPlantas.setAlwaysOnTop(true);
        diagNuevosCamposPlayerPlantas.setIconImage(getIconImage());
        diagNuevosCamposPlayerPlantas.setMaximumSize(new java.awt.Dimension(507, 160));
        diagNuevosCamposPlayerPlantas.setMinimumSize(new java.awt.Dimension(507, 160));
        diagNuevosCamposPlayerPlantas.setModal(true);
        diagNuevosCamposPlayerPlantas.setResizable(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Nuevo Campo");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Ingrese el nuevo campo");

        txtNewCampoPlantas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNewCampoPlantas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNewCampoPlantas.setToolTipText("Nuevo Campo");

        jbAgregarNuevoCampoPlantas.setBackground(java.awt.Color.green);
        jbAgregarNuevoCampoPlantas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbAgregarNuevoCampoPlantas.setText("Nuevo");

        jbFinalizarNuevosCamposPlantas.setBackground(java.awt.Color.red);
        jbFinalizarNuevosCamposPlantas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbFinalizarNuevosCamposPlantas.setText("Finalizar");

        javax.swing.GroupLayout diagNuevosCamposPlayerPlantasLayout = new javax.swing.GroupLayout(diagNuevosCamposPlayerPlantas.getContentPane());
        diagNuevosCamposPlayerPlantas.getContentPane().setLayout(diagNuevosCamposPlayerPlantasLayout);
        diagNuevosCamposPlayerPlantasLayout.setHorizontalGroup(
            diagNuevosCamposPlayerPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagNuevosCamposPlayerPlantasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diagNuevosCamposPlayerPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(diagNuevosCamposPlayerPlantasLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewCampoPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(diagNuevosCamposPlayerPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbFinalizarNuevosCamposPlantas, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jbAgregarNuevoCampoPlantas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        diagNuevosCamposPlayerPlantasLayout.setVerticalGroup(
            diagNuevosCamposPlayerPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagNuevosCamposPlayerPlantasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(diagNuevosCamposPlayerPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diagNuevosCamposPlayerPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtNewCampoPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbAgregarNuevoCampoPlantas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbFinalizarNuevosCamposPlantas)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        diagNuevosCamposPlayerPlantas.getAccessibleContext().setAccessibleParent(diagDatosPlayerPlantas);

        diagDatosPlayerZombies.setTitle("Player Zombies");
        diagDatosPlayerZombies.setIconImage(getIconImage());
        diagDatosPlayerZombies.setMinimumSize(new java.awt.Dimension(540, 280));
        diagDatosPlayerZombies.setModal(true);
        diagDatosPlayerZombies.setResizable(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Ingrese los datos");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Nombre");
        jLabel17.setToolTipText("");

        txtNombrePlayerZombies.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombrePlayerZombies.setToolTipText("Escriba su nombre");

        jbOkDatosPlayerZombies.setBackground(java.awt.Color.green);
        jbOkDatosPlayerZombies.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbOkDatosPlayerZombies.setText("Aceptar");

        jbCancelDatosPlayerZombies.setBackground(java.awt.Color.red);
        jbCancelDatosPlayerZombies.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbCancelDatosPlayerZombies.setText("Cancelar");
        jbCancelDatosPlayerZombies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelDatosPlayerZombiesActionPerformed(evt);
            }
        });

        txtCantidadDatosZombies.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadDatosZombies.setToolTipText("Cuantas plantas quieres?");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Cantidad");

        jbMoreDatosPlayerZombies.setBackground(java.awt.Color.blue);
        jbMoreDatosPlayerZombies.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbMoreDatosPlayerZombies.setText("Agregar mas Campos");
        jbMoreDatosPlayerZombies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMoreDatosPlayerZombiesActionPerformed(evt);
            }
        });

        jbContinuarCatalogoDatosPlayerZombies.setBackground(java.awt.Color.cyan);
        jbContinuarCatalogoDatosPlayerZombies.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbContinuarCatalogoDatosPlayerZombies.setText("Continuar");

        javax.swing.GroupLayout diagDatosPlayerZombiesLayout = new javax.swing.GroupLayout(diagDatosPlayerZombies.getContentPane());
        diagDatosPlayerZombies.getContentPane().setLayout(diagDatosPlayerZombiesLayout);
        diagDatosPlayerZombiesLayout.setHorizontalGroup(
            diagDatosPlayerZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagDatosPlayerZombiesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diagDatosPlayerZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(diagDatosPlayerZombiesLayout.createSequentialGroup()
                        .addGroup(diagDatosPlayerZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(diagDatosPlayerZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(diagDatosPlayerZombiesLayout.createSequentialGroup()
                                .addComponent(jbMoreDatosPlayerZombies)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbContinuarCatalogoDatosPlayerZombies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtCantidadDatosZombies, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtNombrePlayerZombies))
                        .addGap(18, 18, 18)
                        .addGroup(diagDatosPlayerZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbOkDatosPlayerZombies, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCancelDatosPlayerZombies, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diagDatosPlayerZombiesLayout.setVerticalGroup(
            diagDatosPlayerZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagDatosPlayerZombiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(diagDatosPlayerZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtNombrePlayerZombies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbOkDatosPlayerZombies))
                .addGap(18, 18, 18)
                .addGroup(diagDatosPlayerZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCantidadDatosZombies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCancelDatosPlayerZombies))
                .addGap(51, 51, 51)
                .addGroup(diagDatosPlayerZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMoreDatosPlayerZombies)
                    .addComponent(jbContinuarCatalogoDatosPlayerZombies))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        diagNuevosCamposPlayerZombies.setTitle("Nuevos Campos");
        diagNuevosCamposPlayerZombies.setAlwaysOnTop(true);
        diagNuevosCamposPlayerZombies.setIconImage(getIconImage());
        diagNuevosCamposPlayerZombies.setMaximumSize(new java.awt.Dimension(507, 160));
        diagNuevosCamposPlayerZombies.setMinimumSize(new java.awt.Dimension(507, 160));
        diagNuevosCamposPlayerZombies.setModal(true);
        diagNuevosCamposPlayerZombies.setResizable(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Nuevo Campo");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 153));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Ingrese el nuevo campo");

        txtNewCampoZombies.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNewCampoZombies.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNewCampoZombies.setToolTipText("Nuevo Campo");

        jbAgregarNuevoCampoZombies.setBackground(java.awt.Color.green);
        jbAgregarNuevoCampoZombies.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbAgregarNuevoCampoZombies.setText("Nuevo");

        jbFinalizarNuevosCamposZombies.setBackground(java.awt.Color.red);
        jbFinalizarNuevosCamposZombies.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbFinalizarNuevosCamposZombies.setText("Finalizar");

        javax.swing.GroupLayout diagNuevosCamposPlayerZombiesLayout = new javax.swing.GroupLayout(diagNuevosCamposPlayerZombies.getContentPane());
        diagNuevosCamposPlayerZombies.getContentPane().setLayout(diagNuevosCamposPlayerZombiesLayout);
        diagNuevosCamposPlayerZombiesLayout.setHorizontalGroup(
            diagNuevosCamposPlayerZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagNuevosCamposPlayerZombiesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diagNuevosCamposPlayerZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(diagNuevosCamposPlayerZombiesLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewCampoZombies, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(diagNuevosCamposPlayerZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbFinalizarNuevosCamposZombies, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jbAgregarNuevoCampoZombies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        diagNuevosCamposPlayerZombiesLayout.setVerticalGroup(
            diagNuevosCamposPlayerZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagNuevosCamposPlayerZombiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(diagNuevosCamposPlayerZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diagNuevosCamposPlayerZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(txtNewCampoZombies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbAgregarNuevoCampoZombies))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbFinalizarNuevosCamposZombies)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        diagCatalogoPlantas.setTitle("Creacion de Catalogo de Plantas");
        diagCatalogoPlantas.setMaximumSize(new java.awt.Dimension(635, 300));
        diagCatalogoPlantas.setMinimumSize(new java.awt.Dimension(635, 300));
        diagCatalogoPlantas.setModal(true);
        diagCatalogoPlantas.setPreferredSize(new java.awt.Dimension(635, 300));
        diagCatalogoPlantas.setResizable(false);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        botonAgregarPlantasCatalogo.setBackground(java.awt.Color.green);
        botonAgregarPlantasCatalogo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonAgregarPlantasCatalogo.setText("Agregar plantas");
        botonAgregarPlantasCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPlantasCatalogoActionPerformed(evt);
            }
        });

        botonFinalizaDatosPlayerPlantas.setBackground(java.awt.Color.blue);
        botonFinalizaDatosPlayerPlantas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonFinalizaDatosPlayerPlantas.setText("Finalizar");
        botonFinalizaDatosPlayerPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizaDatosPlayerPlantasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diagCatalogoPlantasLayout = new javax.swing.GroupLayout(diagCatalogoPlantas.getContentPane());
        diagCatalogoPlantas.getContentPane().setLayout(diagCatalogoPlantasLayout);
        diagCatalogoPlantasLayout.setHorizontalGroup(
            diagCatalogoPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagCatalogoPlantasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneCatalogoPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diagCatalogoPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregarPlantasCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonFinalizaDatosPlayerPlantas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        diagCatalogoPlantasLayout.setVerticalGroup(
            diagCatalogoPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagCatalogoPlantasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diagCatalogoPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneCatalogoPlantas, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap())
            .addGroup(diagCatalogoPlantasLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(botonAgregarPlantasCatalogo)
                .addGap(42, 42, 42)
                .addComponent(botonFinalizaDatosPlayerPlantas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        diagCatalogoPlantas.getAccessibleContext().setAccessibleParent(diagDatosPlayerPlantas);

        diagNuevaPlanta.setTitle("Nueva Planta");
        diagNuevaPlanta.setBackground(java.awt.Color.black);
        diagNuevaPlanta.setIconImage(getIconImage());
        diagNuevaPlanta.setMaximumSize(new java.awt.Dimension(620, 430));
        diagNuevaPlanta.setMinimumSize(new java.awt.Dimension(620, 430));
        diagNuevaPlanta.setModal(true);
        diagNuevaPlanta.setPreferredSize(new java.awt.Dimension(620, 430));
        diagNuevaPlanta.setResizable(false);
        diagNuevaPlanta.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                diagNuevaPlantaWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese la nueva Planta");
        jLabel1.setPreferredSize(new java.awt.Dimension(282, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Puntos Ataque");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Puntos Defensa");

        etiquetaImagenPlanta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaImagenPlanta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etiquetaImagenPlanta.setEnabled(false);
        etiquetaImagenPlanta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiquetaImagenPlantaMouseClicked(evt);
            }
        });

        txtNombrePlantaNueva.setEnabled(false);

        txtPuntosAtaquePlantaNueva.setEnabled(false);

        txtPuntosDefensaPlantaNueva.setEnabled(false);

        botonNuevaPlanta.setBackground(java.awt.Color.cyan);
        botonNuevaPlanta.setText("Nuevo");
        botonNuevaPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaPlantaActionPerformed(evt);
            }
        });

        botonGuardarPlantaNueva.setBackground(java.awt.Color.green);
        botonGuardarPlantaNueva.setText("Guardar");
        botonGuardarPlantaNueva.setEnabled(false);
        botonGuardarPlantaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarPlantaNuevaActionPerformed(evt);
            }
        });

        botonSalirIngresoPlantaNueva.setBackground(java.awt.Color.red);
        botonSalirIngresoPlantaNueva.setText("Salir");
        botonSalirIngresoPlantaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirIngresoPlantaNuevaActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tipo Ataque");

        txtTipoAtaquePlantaNueva.setEnabled(false);

        botonConfirmNewPlanta.setBackground(java.awt.Color.green);
        botonConfirmNewPlanta.setEnabled(false);
        botonConfirmNewPlanta.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        botonConfirmNewPlanta.setLabel("Si");
        botonConfirmNewPlanta.setMaximumSize(new java.awt.Dimension(45, 25));
        botonConfirmNewPlanta.setMinimumSize(new java.awt.Dimension(45, 25));
        botonConfirmNewPlanta.setPreferredSize(new java.awt.Dimension(45, 25));
        botonConfirmNewPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmNewPlantaActionPerformed(evt);
            }
        });

        labelConfirmacionNuevaPlanta.setAlignment(java.awt.Label.CENTER);
        labelConfirmacionNuevaPlanta.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelConfirmacionNuevaPlanta.setForeground(java.awt.Color.red);
        labelConfirmacionNuevaPlanta.setMaximumSize(new java.awt.Dimension(390, 20));
        labelConfirmacionNuevaPlanta.setMinimumSize(new java.awt.Dimension(390, 20));
        labelConfirmacionNuevaPlanta.setPreferredSize(new java.awt.Dimension(390, 20));
        labelConfirmacionNuevaPlanta.setText("Confirma que lo desea agregar?");

        botonAbortNewPlanta.setBackground(java.awt.Color.red);
        botonAbortNewPlanta.setEnabled(false);
        botonAbortNewPlanta.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        botonAbortNewPlanta.setLabel("No");
        botonAbortNewPlanta.setMaximumSize(new java.awt.Dimension(45, 25));
        botonAbortNewPlanta.setMinimumSize(new java.awt.Dimension(45, 25));
        botonAbortNewPlanta.setPreferredSize(new java.awt.Dimension(45, 25));
        botonAbortNewPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbortNewPlantaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diagNuevaPlantaLayout = new javax.swing.GroupLayout(diagNuevaPlanta.getContentPane());
        diagNuevaPlanta.getContentPane().setLayout(diagNuevaPlantaLayout);
        diagNuevaPlantaLayout.setHorizontalGroup(
            diagNuevaPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagNuevaPlantaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diagNuevaPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(diagNuevaPlantaLayout.createSequentialGroup()
                        .addGroup(diagNuevaPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(diagNuevaPlantaLayout.createSequentialGroup()
                                .addGroup(diagNuevaPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(botonNuevaPlanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(diagNuevaPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTipoAtaquePlantaNueva)
                                    .addComponent(txtPuntosAtaquePlantaNueva)
                                    .addComponent(txtPuntosDefensaPlantaNueva)
                                    .addComponent(txtNombrePlantaNueva)
                                    .addGroup(diagNuevaPlantaLayout.createSequentialGroup()
                                        .addComponent(botonGuardarPlantaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonSalirIngresoPlantaNueva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(diagNuevaPlantaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonConfirmNewPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(botonAbortNewPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85))
                            .addComponent(labelConfirmacionNuevaPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(etiquetaImagenPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        diagNuevaPlantaLayout.setVerticalGroup(
            diagNuevaPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagNuevaPlantaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diagNuevaPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaImagenPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(diagNuevaPlantaLayout.createSequentialGroup()
                        .addGroup(diagNuevaPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombrePlantaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(diagNuevaPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPuntosAtaquePlantaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(diagNuevaPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtPuntosDefensaPlantaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(diagNuevaPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtTipoAtaquePlantaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(diagNuevaPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonSalirIngresoPlantaNueva)
                            .addComponent(botonGuardarPlantaNueva)
                            .addComponent(botonNuevaPlanta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelConfirmacionNuevaPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(diagNuevaPlantaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAbortNewPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonConfirmNewPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        diagNuevaPlanta.getAccessibleContext().setAccessibleParent(diagCatalogoPlantas);

        jFileChooserFotos.setCurrentDirectory(new java.io.File("C:\\Photographs"));
        jFileChooserFotos.setFileFilter(filtroFotos);
        jFileChooserFotos.setMaximumSize(new java.awt.Dimension(640, 410));
        jFileChooserFotos.setMinimumSize(new java.awt.Dimension(640, 410));
        jFileChooserFotos.setPreferredSize(new java.awt.Dimension(640, 410));

        diagCatalogoPlantas1.setTitle("Creacion de Catalogo de Plantas");
        diagCatalogoPlantas1.setMaximumSize(new java.awt.Dimension(635, 300));
        diagCatalogoPlantas1.setMinimumSize(new java.awt.Dimension(635, 300));
        diagCatalogoPlantas1.setModal(true);
        diagCatalogoPlantas1.setPreferredSize(new java.awt.Dimension(635, 300));
        diagCatalogoPlantas1.setResizable(false);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        botonAgregarPlantasCatalogo1.setBackground(java.awt.Color.green);
        botonAgregarPlantasCatalogo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonAgregarPlantasCatalogo1.setText("Agregar plantas");
        botonAgregarPlantasCatalogo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPlantasCatalogo1ActionPerformed(evt);
            }
        });

        botonFinalizaDatosPlayerPlantas1.setBackground(java.awt.Color.blue);
        botonFinalizaDatosPlayerPlantas1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonFinalizaDatosPlayerPlantas1.setText("Finalizar");
        botonFinalizaDatosPlayerPlantas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizaDatosPlayerPlantas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diagCatalogoPlantas1Layout = new javax.swing.GroupLayout(diagCatalogoPlantas1.getContentPane());
        diagCatalogoPlantas1.getContentPane().setLayout(diagCatalogoPlantas1Layout);
        diagCatalogoPlantas1Layout.setHorizontalGroup(
            diagCatalogoPlantas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagCatalogoPlantas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneCatalogoPlantas1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diagCatalogoPlantas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregarPlantasCatalogo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonFinalizaDatosPlayerPlantas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        diagCatalogoPlantas1Layout.setVerticalGroup(
            diagCatalogoPlantas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagCatalogoPlantas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diagCatalogoPlantas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneCatalogoPlantas1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(jSeparator3))
                .addContainerGap())
            .addGroup(diagCatalogoPlantas1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(botonAgregarPlantasCatalogo1)
                .addGap(42, 42, 42)
                .addComponent(botonFinalizaDatosPlayerPlantas1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        diagNuevaPlanta1.setTitle("Nueva Planta");
        diagNuevaPlanta1.setBackground(java.awt.Color.black);
        diagNuevaPlanta1.setIconImage(getIconImage());
        diagNuevaPlanta1.setMaximumSize(new java.awt.Dimension(620, 430));
        diagNuevaPlanta1.setMinimumSize(new java.awt.Dimension(620, 430));
        diagNuevaPlanta1.setModal(true);
        diagNuevaPlanta1.setPreferredSize(new java.awt.Dimension(620, 430));
        diagNuevaPlanta1.setResizable(false);
        diagNuevaPlanta1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                diagNuevaPlanta1WindowOpened(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ingrese la nueva Planta");
        jLabel5.setPreferredSize(new java.awt.Dimension(282, 40));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nombre");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Puntos Ataque");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Puntos Defensa");

        etiquetaImagenPlanta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaImagenPlanta1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        etiquetaImagenPlanta1.setEnabled(false);
        etiquetaImagenPlanta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiquetaImagenPlanta1MouseClicked(evt);
            }
        });

        txtNombrePlantaNueva1.setEnabled(false);

        txtPuntosAtaquePlantaNueva1.setEnabled(false);

        txtPuntosDefensaPlantaNueva1.setEnabled(false);

        botonNuevaPlanta1.setBackground(java.awt.Color.cyan);
        botonNuevaPlanta1.setText("Nuevo");
        botonNuevaPlanta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaPlanta1ActionPerformed(evt);
            }
        });

        botonGuardarPlantaNueva1.setBackground(java.awt.Color.green);
        botonGuardarPlantaNueva1.setText("Guardar");
        botonGuardarPlantaNueva1.setEnabled(false);
        botonGuardarPlantaNueva1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarPlantaNueva1ActionPerformed(evt);
            }
        });

        botonSalirIngresoPlantaNueva1.setBackground(java.awt.Color.red);
        botonSalirIngresoPlantaNueva1.setText("Salir");
        botonSalirIngresoPlantaNueva1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirIngresoPlantaNueva1ActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Tipo Ataque");

        txtTipoAtaquePlantaNueva1.setEnabled(false);

        botonConfirmNewPlanta1.setBackground(java.awt.Color.green);
        botonConfirmNewPlanta1.setEnabled(false);
        botonConfirmNewPlanta1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        botonConfirmNewPlanta1.setLabel("Si");
        botonConfirmNewPlanta1.setMaximumSize(new java.awt.Dimension(45, 25));
        botonConfirmNewPlanta1.setMinimumSize(new java.awt.Dimension(45, 25));
        botonConfirmNewPlanta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmNewPlanta1ActionPerformed(evt);
            }
        });

        labelConfirmacionNuevaPlanta1.setAlignment(java.awt.Label.CENTER);
        labelConfirmacionNuevaPlanta1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelConfirmacionNuevaPlanta1.setForeground(java.awt.Color.red);
        labelConfirmacionNuevaPlanta1.setMaximumSize(new java.awt.Dimension(390, 20));
        labelConfirmacionNuevaPlanta1.setMinimumSize(new java.awt.Dimension(390, 20));
        labelConfirmacionNuevaPlanta1.setText("Confirma que lo desea agregar?");

        botonAbortNewPlanta1.setBackground(java.awt.Color.red);
        botonAbortNewPlanta1.setEnabled(false);
        botonAbortNewPlanta1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        botonAbortNewPlanta1.setLabel("No");
        botonAbortNewPlanta1.setMaximumSize(new java.awt.Dimension(45, 25));
        botonAbortNewPlanta1.setMinimumSize(new java.awt.Dimension(45, 25));
        botonAbortNewPlanta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbortNewPlanta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diagNuevaPlanta1Layout = new javax.swing.GroupLayout(diagNuevaPlanta1.getContentPane());
        diagNuevaPlanta1.getContentPane().setLayout(diagNuevaPlanta1Layout);
        diagNuevaPlanta1Layout.setHorizontalGroup(
            diagNuevaPlanta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagNuevaPlanta1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diagNuevaPlanta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(diagNuevaPlanta1Layout.createSequentialGroup()
                        .addGroup(diagNuevaPlanta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(diagNuevaPlanta1Layout.createSequentialGroup()
                                .addGroup(diagNuevaPlanta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(botonNuevaPlanta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(diagNuevaPlanta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTipoAtaquePlantaNueva1)
                                    .addComponent(txtPuntosAtaquePlantaNueva1)
                                    .addComponent(txtPuntosDefensaPlantaNueva1)
                                    .addComponent(txtNombrePlantaNueva1)
                                    .addGroup(diagNuevaPlanta1Layout.createSequentialGroup()
                                        .addComponent(botonGuardarPlantaNueva1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonSalirIngresoPlantaNueva1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(diagNuevaPlanta1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonConfirmNewPlanta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(botonAbortNewPlanta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85))
                            .addComponent(labelConfirmacionNuevaPlanta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(etiquetaImagenPlanta1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        diagNuevaPlanta1Layout.setVerticalGroup(
            diagNuevaPlanta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagNuevaPlanta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diagNuevaPlanta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaImagenPlanta1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(diagNuevaPlanta1Layout.createSequentialGroup()
                        .addGroup(diagNuevaPlanta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNombrePlantaNueva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(diagNuevaPlanta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtPuntosAtaquePlantaNueva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(diagNuevaPlanta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtPuntosDefensaPlantaNueva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(diagNuevaPlanta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtTipoAtaquePlantaNueva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(diagNuevaPlanta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonSalirIngresoPlantaNueva1)
                            .addComponent(botonGuardarPlantaNueva1)
                            .addComponent(botonNuevaPlanta1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelConfirmacionNuevaPlanta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(diagNuevaPlanta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonAbortNewPlanta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonConfirmNewPlanta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Planta versus Zombies Guatemalteco");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setResizable(false);

        jbPlayerPlantas.setBackground(java.awt.Color.green);
        jbPlayerPlantas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbPlayerPlantas.setText("Player Plantas");
        jbPlayerPlantas.setToolTipText("Plantas");
        jbPlayerPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPlayerPlantasActionPerformed(evt);
            }
        });

        jbPlayerZombie.setBackground(new java.awt.Color(255, 51, 0));
        jbPlayerZombie.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbPlayerZombie.setText("Player Zombies");
        jbPlayerZombie.setToolTipText("Zombies");
        jbPlayerZombie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPlayerZombieActionPerformed(evt);
            }
        });

        jbStartJuego.setBackground(java.awt.Color.blue);
        jbStartJuego.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbStartJuego.setText("Comenzar ");
        jbStartJuego.setToolTipText("Start");
        jbStartJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStartJuegoActionPerformed(evt);
            }
        });

        jbEliminarDatos.setBackground(java.awt.Color.gray);
        jbEliminarDatos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbEliminarDatos.setText("Eliminar Datos");
        jbEliminarDatos.setToolTipText("Borrar Datos");
        jbEliminarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarDatosActionPerformed(evt);
            }
        });

        jlabelPlanta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelZombie.setForeground(new java.awt.Color(255, 255, 255));
        jLabelZombie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(437, 437, 437)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbStartJuego, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbPlayerPlantas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbEliminarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbPlayerZombie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jlabelPlanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelZombie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabelPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPlayerPlantas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPlayerZombie)
                .addGap(30, 30, 30)
                .addComponent(jbEliminarDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbStartJuego)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPlayerPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPlayerPlantasActionPerformed
        diagDatosPlayerPlantas.setLocationRelativeTo(null);
        diagDatosPlayerPlantas.show();
        diagDatosPlayerPlantas.setModal(true);
        
    }//GEN-LAST:event_jbPlayerPlantasActionPerformed

    private void jbPlayerZombieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPlayerZombieActionPerformed
        diagDatosPlayerZombies.setLocationRelativeTo(null);
        diagDatosPlayerZombies.show();
        diagDatosPlayerZombies.setModal(true);
    }//GEN-LAST:event_jbPlayerZombieActionPerformed

    private void jbEliminarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEliminarDatosActionPerformed

    private void jbStartJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStartJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbStartJuegoActionPerformed

    private void jbCancelDatosPlayerPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelDatosPlayerPlantasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelDatosPlayerPlantasActionPerformed

    private void jbMoreDatosPlayerPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMoreDatosPlayerPlantasActionPerformed
        // TODO add your handling code here:
        diagNuevosCamposPlayerPlantas.setLocationRelativeTo(null);
        diagNuevosCamposPlayerPlantas.show();
        diagNuevosCamposPlayerPlantas.setModal(true);
    }//GEN-LAST:event_jbMoreDatosPlayerPlantasActionPerformed

    private void jbCancelDatosPlayerZombiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelDatosPlayerZombiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelDatosPlayerZombiesActionPerformed

    private void jbMoreDatosPlayerZombiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMoreDatosPlayerZombiesActionPerformed
        diagNuevosCamposPlayerZombies.setLocationRelativeTo(null);
        diagNuevosCamposPlayerZombies.show();
        diagNuevosCamposPlayerZombies.setModal(true);
    }//GEN-LAST:event_jbMoreDatosPlayerZombiesActionPerformed

    private void jbContinuarCatalogoDatosPlayerPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbContinuarCatalogoDatosPlayerPlantasActionPerformed
        diagCatalogoPlantas.setLocationRelativeTo(null);
        diagCatalogoPlantas.show();
        diagCatalogoPlantas.setModal(true);
    }//GEN-LAST:event_jbContinuarCatalogoDatosPlayerPlantasActionPerformed

    private void botonFinalizaDatosPlayerPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizaDatosPlayerPlantasActionPerformed
        // TODO add your handling code here:
        diagCatalogoPlantas.hide();
        diagDatosPlayerPlantas.hide();
        jbPlayerPlantas.setEnabled(false);
    }//GEN-LAST:event_botonFinalizaDatosPlayerPlantasActionPerformed

    private void limpiarTextosNuevaPlanta()
    {
        txtNombrePlantaNueva.setText("");
        txtPuntosAtaquePlantaNueva.setText("");
        txtPuntosDefensaPlantaNueva.setText("");
        txtTipoAtaquePlantaNueva.setText("");
    }
    
    private void botonNuevaPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaPlantaActionPerformed
        txtNombrePlantaNueva.setEnabled(true);
        txtPuntosAtaquePlantaNueva.setEnabled(true);
        txtPuntosDefensaPlantaNueva.setEnabled(true);
        txtTipoAtaquePlantaNueva.setEnabled(true);
        etiquetaImagenPlanta.setEnabled(true);
        botonNuevaPlanta.setEnabled(false);
        botonGuardarPlantaNueva.setEnabled(true);
        botonSalirIngresoPlantaNueva.setEnabled(false);
    }//GEN-LAST:event_botonNuevaPlantaActionPerformed

    private void botonConfirmNewPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmNewPlantaActionPerformed
        //Primero inserto la planta al listado del catalogo 
        txtNombrePlantaNueva.setEnabled(false);
        txtPuntosAtaquePlantaNueva.setEnabled(false);
        txtPuntosDefensaPlantaNueva.setEnabled(false);
        txtTipoAtaquePlantaNueva.setEnabled(false);
        etiquetaImagenPlanta.setEnabled(false);
        botonNuevaPlanta.setEnabled(true);
        botonGuardarPlantaNueva.setEnabled(false);
        labelConfirmacionNuevaPlanta.setVisible(false);
        botonSalirIngresoPlantaNueva.setEnabled(true);
        labelConfirmacionNuevaPlanta.setVisible(false);
        botonAbortNewPlanta.setEnabled(false);
        botonConfirmNewPlanta.setEnabled(false);
        botonAbortNewPlanta.setVisible(false);
        botonConfirmNewPlanta.setVisible(false);        
        limpiarTextosNuevaPlanta();
    }//GEN-LAST:event_botonConfirmNewPlantaActionPerformed

    private void botonAbortNewPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbortNewPlantaActionPerformed
        txtNombrePlantaNueva.setEnabled(false);
        txtPuntosAtaquePlantaNueva.setEnabled(false);
        txtPuntosDefensaPlantaNueva.setEnabled(false);
        txtTipoAtaquePlantaNueva.setEnabled(false);
        etiquetaImagenPlanta.setEnabled(false);
        botonNuevaPlanta.setEnabled(true);
        botonGuardarPlantaNueva.setEnabled(false);
        labelConfirmacionNuevaPlanta.setVisible(false);
        botonSalirIngresoPlantaNueva.setEnabled(true);
        labelConfirmacionNuevaPlanta.setVisible(false);
        botonAbortNewPlanta.setEnabled(false);
        botonConfirmNewPlanta.setEnabled(false);
        botonAbortNewPlanta.setVisible(false);
        botonConfirmNewPlanta.setVisible(false);        
        limpiarTextosNuevaPlanta();
    }//GEN-LAST:event_botonAbortNewPlantaActionPerformed

    private void botonGuardarPlantaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarPlantaNuevaActionPerformed
        labelConfirmacionNuevaPlanta.setVisible(true);
        botonConfirmNewPlanta.setEnabled(true);
        botonAbortNewPlanta.setEnabled(true);
        botonConfirmNewPlanta.setVisible(true);
        botonAbortNewPlanta.setVisible(true);        
        botonSalirIngresoPlantaNueva.setEnabled(false);
        botonGuardarPlantaNueva.setEnabled(false);
        botonNuevaPlanta.setEnabled(false);
    }//GEN-LAST:event_botonGuardarPlantaNuevaActionPerformed

    private void botonSalirIngresoPlantaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirIngresoPlantaNuevaActionPerformed
        limpiarTextosNuevaPlanta();
    }//GEN-LAST:event_botonSalirIngresoPlantaNuevaActionPerformed

    private void botonAgregarPlantasCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPlantasCatalogoActionPerformed
        diagNuevaPlanta.setLocationRelativeTo(null);
        limpiarTextosNuevaPlanta();       
        diagNuevaPlanta.show();       
        diagNuevaPlanta.setModal(true);        
        //ponerImagenLabel(pathPlantaImageDefault, etiquetaImagenPlanta);
    }//GEN-LAST:event_botonAgregarPlantasCatalogoActionPerformed

    private void etiquetaImagenPlantaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaImagenPlantaMouseClicked
        int resuul = jFileChooserFotos.showOpenDialog(diagNuevaPlanta); 
        if(resuul == jFileChooserFotos.APPROVE_OPTION){
        foto = jFileChooserFotos.getSelectedFile().getPath();
            if(!foto.isEmpty()){
                ImageIcon fot = new ImageIcon(foto);
                Icon icono = new ImageIcon(fot.getImage().getScaledInstance(etiquetaImagenPlanta.getWidth(), etiquetaImagenPlanta.getHeight(), Image.SCALE_DEFAULT));
                etiquetaImagenPlanta.setIcon(icono);        
                this.repaint();
            }
        }
    }//GEN-LAST:event_etiquetaImagenPlantaMouseClicked

    private void diagNuevaPlantaWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_diagNuevaPlantaWindowOpened
//        labelConfirmacionNuevaPlanta.setVisible(false);
//        botonConfirmNewPlanta.setEnabled(false);
//        botonAbortNewPlanta.setEnabled(false);
//        botonConfirmNewPlanta.setVisible(false);
//        botonAbortNewPlanta.setVisible(false);
        ponerImagenLabel(pathPlantaImageDefault, etiquetaImagenPlanta);
    }//GEN-LAST:event_diagNuevaPlantaWindowOpened

    private void botonAgregarPlantasCatalogo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPlantasCatalogo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarPlantasCatalogo1ActionPerformed

    private void botonFinalizaDatosPlayerPlantas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizaDatosPlayerPlantas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFinalizaDatosPlayerPlantas1ActionPerformed

    private void etiquetaImagenPlanta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiquetaImagenPlanta1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_etiquetaImagenPlanta1MouseClicked

    private void botonNuevaPlanta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaPlanta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNuevaPlanta1ActionPerformed

    private void botonGuardarPlantaNueva1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarPlantaNueva1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarPlantaNueva1ActionPerformed

    private void botonSalirIngresoPlantaNueva1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirIngresoPlantaNueva1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirIngresoPlantaNueva1ActionPerformed

    private void botonConfirmNewPlanta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmNewPlanta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConfirmNewPlanta1ActionPerformed

    private void botonAbortNewPlanta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbortNewPlanta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAbortNewPlanta1ActionPerformed

    private void diagNuevaPlanta1WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_diagNuevaPlanta1WindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_diagNuevaPlanta1WindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Mi_Ventana_200412823 jf = new Inicio();
                jf.setLocationRelativeTo(null);                
                jf.setVisible(true);
            }
        });
    }
    
    /**
     * Sobrecarga del metodo para utilizar un icono personalizado para la aplicacion
     */
    @Override
     public Image getIconImage() 
    {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/icono.png"));
        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Button botonAbortNewPlanta;
    public java.awt.Button botonAbortNewPlanta1;
    private javax.swing.JButton botonAgregarPlantasCatalogo;
    private javax.swing.JButton botonAgregarPlantasCatalogo1;
    public java.awt.Button botonConfirmNewPlanta;
    public java.awt.Button botonConfirmNewPlanta1;
    private javax.swing.JButton botonFinalizaDatosPlayerPlantas;
    private javax.swing.JButton botonFinalizaDatosPlayerPlantas1;
    private javax.swing.JButton botonGuardarPlantaNueva;
    private javax.swing.JButton botonGuardarPlantaNueva1;
    private javax.swing.JButton botonNuevaPlanta;
    private javax.swing.JButton botonNuevaPlanta1;
    private javax.swing.JButton botonSalirIngresoPlantaNueva;
    private javax.swing.JButton botonSalirIngresoPlantaNueva1;
    private javax.swing.JDialog diagCatalogoPlantas;
    private javax.swing.JDialog diagCatalogoPlantas1;
    private javax.swing.JDialog diagDatosPlayerPlantas;
    private javax.swing.JDialog diagDatosPlayerZombies;
    private javax.swing.JDialog diagNuevaPlanta;
    private javax.swing.JDialog diagNuevaPlanta1;
    private javax.swing.JDialog diagNuevosCamposPlayerPlantas;
    private javax.swing.JDialog diagNuevosCamposPlayerZombies;
    private javax.swing.JLabel etiquetaImagenPlanta;
    private javax.swing.JLabel etiquetaImagenPlanta1;
    private javax.swing.JFileChooser jFileChooserFotos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelZombie;
    private javax.swing.JScrollPane jScrollPaneCatalogoPlantas;
    private javax.swing.JScrollPane jScrollPaneCatalogoPlantas1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbAgregarNuevoCampoPlantas;
    private javax.swing.JButton jbAgregarNuevoCampoZombies;
    private javax.swing.JButton jbCancelDatosPlayerPlantas;
    private javax.swing.JButton jbCancelDatosPlayerZombies;
    private javax.swing.JButton jbContinuarCatalogoDatosPlayerPlantas;
    private javax.swing.JButton jbContinuarCatalogoDatosPlayerZombies;
    private javax.swing.JButton jbEliminarDatos;
    private javax.swing.JButton jbFinalizarNuevosCamposPlantas;
    private javax.swing.JButton jbFinalizarNuevosCamposZombies;
    private javax.swing.JButton jbMoreDatosPlayerPlantas;
    private javax.swing.JButton jbMoreDatosPlayerZombies;
    private javax.swing.JButton jbOkDatosPlayerPlantas;
    private javax.swing.JButton jbOkDatosPlayerZombies;
    public javax.swing.JButton jbPlayerPlantas;
    private javax.swing.JButton jbPlayerZombie;
    private javax.swing.JButton jbStartJuego;
    private javax.swing.JLabel jlabelPlanta;
    public java.awt.Label labelConfirmacionNuevaPlanta;
    public java.awt.Label labelConfirmacionNuevaPlanta1;
    private javax.swing.JTextField txtCantidadDatosPlantas;
    private javax.swing.JTextField txtCantidadDatosZombies;
    private javax.swing.JTextField txtNewCampoPlantas;
    private javax.swing.JTextField txtNewCampoZombies;
    private javax.swing.JTextField txtNombrePlantaNueva;
    private javax.swing.JTextField txtNombrePlantaNueva1;
    private javax.swing.JTextField txtNombrePlayerPlantas;
    private javax.swing.JTextField txtNombrePlayerZombies;
    private javax.swing.JTextField txtPuntosAtaquePlantaNueva;
    private javax.swing.JTextField txtPuntosAtaquePlantaNueva1;
    private javax.swing.JTextField txtPuntosDefensaPlantaNueva;
    private javax.swing.JTextField txtPuntosDefensaPlantaNueva1;
    private javax.swing.JTextField txtTipoAtaquePlantaNueva;
    private javax.swing.JTextField txtTipoAtaquePlantaNueva1;
    // End of variables declaration//GEN-END:variables
}
